<a href="https://colab.research.google.com/github/AbidYousuf/Abid-Yousuf/blob/main/DLLabp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
image_height = int(input("Enter image height: "))
image_width = int(input("Enter image width: "))
filter_height = int(input("Enter filter height: "))
filter_width = int(input("Enter filter width: "))
stride = int(input("Enter stride value: "))

Enter image height: 7
Enter image width: 7
Enter filter height: 3
Enter filter width: 3
Enter stride value: 2


In [ ]:
image = np.random.randint(0, 255, size=(image_height, image_width))
kernel = np.random.randint(-1, 2, size=(filter_height, filter_width))

In [ ]:
def convolution(image, kernel, stride):
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape

    output_height = (image_height - kernel_height) // stride + 1
    output_width = (image_width - kernel_width) // stride + 1

    output = np.zeros((output_height, output_width))

    for i in range(0, output_height * stride, stride):
        for j in range(0, output_width * stride, stride):

            imgk = image[i:i + kernel_height, j:j + kernel_width]


            if imgk.shape == kernel.shape:

                output[i // stride, j // stride] = np.sum(imgk * kernel)

    return output

In [ ]:
result = convolution(image, kernel, stride)

In [ ]:
print("\nOriginal Image:")
print(image)
print("\nFilter:")
print(kernel)
print("\nConvolution Result:")
print(result)


Original Image:
[[123 184 212 234 181 102   9]
 [215  26 122  64 101  63 120]
 [ 51 182  75  96  77  23 229]
 [136   8 234 150  68 212 110]
 [214  59 201  25 205  32  39]
 [ 69 154 239 153 180  98 203]
 [233 195  62 212 140 207 252]]

Filter:
[[-1 -1  1]
 [ 1  0  1]
 [ 0  0  0]]

Convolution Result:
[[242. -42. -53.]
 [212. 208. 307.]
 [236. 398. 185.]]
